name: moovit_app
description: A location-based Flutter application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  google_sign_in: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  app_links: ^6.3.2
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon-black.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/pin-icon.png"
  web:
    generate: true
    image_path: "assets/images/app-icon-black.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
